#!/usr/bin/env bash
# Issue #125 full-stack video-thumbnail smoke test.
#
# Generates a small synthetic video into a temp dir (same
# `ffmpeg`-via-`homeai-exec-toolbox` convention as
# `media_browser_smoke.sh`'s own `seed_test_video` — see that script's
# header for exactly why: ffmpeg lives in that image, not necessarily on
# this host), uploads it into the e2e user's Personal space via the
# platform files API, opens a real headless browser against the live stack,
# navigates to the Files tab, and asserts the row shows a real, decoded
# poster-frame thumbnail `<img>` (server-generated via
# `GET /api/platform/files/thumbnail`, `app/core/thumbnails.py`) instead of the
# generic `videocam-outline` icon — see `video_thumbnail_browser_smoke.mjs`
# for the exact step-by-step. Cleans up the seeded file on any exit
# (success or failure).
#
# Prerequisites (not managed by this script — same convention as
# `media_browser_smoke.sh`/`image_browser_smoke.sh`):
#   - The full docker-compose stack is up and healthy:
#       docker compose up -d
#     (rebuild `caddy`/`platform` first if either changed:
#       docker compose up -d --build --no-deps caddy platform
#     — thumbnails are generated by `platform`, whose image carries
#     `ffmpeg` since M11-01.)
#   - Node.js/npm available on PATH (e.g. via nvm).
#   - `docker` available on PATH, and the `homeai-exec-toolbox:latest`
#     image already built (`services/code-exec-manager/build-exec-image.sh`).
#
# Usage:
#   scripts/e2e/video_thumbnail_browser_smoke.sh
#   VIDEO_THUMBNAIL_SMOKE_BASE_URL=http://homeai.local/ scripts/e2e/video_thumbnail_browser_smoke.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

VIDEO_FILE_NAME="video-thumbnail-browser-smoke-test-video.mp4"

# M11-01: the clip is generated into a temp dir and uploaded by the .mjs
# through the platform files API as the e2e user (it lands in that user's
# Personal space and goes away with the user), never into a host files dir.
SEED_DIR="$(mktemp -d)"
VIDEO_SEED_PATH="${SEED_DIR}/${VIDEO_FILE_NAME}"

log() {
  echo "[video-thumbnail-browser-smoke] $(date '+%H:%M:%S') $*"
}

seed_test_video() {
  log "Generating ${VIDEO_SEED_PATH} via ffmpeg (homeai-exec-toolbox)..."
  docker run --rm --user "$(id -u):$(id -g)" -v "${SEED_DIR}:/w" homeai-exec-toolbox:latest \
    ffmpeg -y -f lavfi -i "testsrc=duration=3:size=320x240:rate=10" -pix_fmt yuv420p "/w/${VIDEO_FILE_NAME}"
  if [ ! -f "$VIDEO_SEED_PATH" ]; then
    log "ERROR: ${VIDEO_SEED_PATH} was not created"
    exit 1
  fi
  log "OK: generated ${VIDEO_SEED_PATH} ($(stat -c%s "$VIDEO_SEED_PATH") bytes)"
}

cleanup() {
  rm -rf "$SEED_DIR" 2>/dev/null || true
}
trap cleanup EXIT

cd "$SCRIPT_DIR"

if [ ! -d node_modules/playwright ]; then
  echo "==> Installing Playwright (npm install)..."
  npm install
fi

echo "==> Ensuring the Chromium browser binary is installed..."
npx playwright install chromium

seed_test_video

echo "==> Running the smoke test against ${VIDEO_THUMBNAIL_SMOKE_BASE_URL:-http://localhost/}..."
VIDEO_THUMBNAIL_SMOKE_FILE_PATH="$VIDEO_SEED_PATH" node "$SCRIPT_DIR/video_thumbnail_browser_smoke.mjs"
